import os
import re
import sqlite3
from collections import defaultdict, deque
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


# ============================================================
# CONFIG
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env")
load_dotenv()

DB_PATH = BASE_DIR / "data" / "exchange_wallets.db"
if not DB_PATH.exists():
    alt_db = BASE_DIR.parent / "data" / "exchange_wallets.db"
    if alt_db.exists():
        DB_PATH = alt_db

ALCHEMY_API_KEY = os.getenv("ALCHEMY_API_KEY", "").strip()
ALCHEMY_URL = (
    f"https://eth-mainnet.g.alchemy.com/v2/{ALCHEMY_API_KEY}"
    if ALCHEMY_API_KEY
    else ""
)

MAX_TX_PER_REQUEST = 10
MAX_TOTAL_TX = 100
MAX_WALLETS = 20

# Optional entity registry.
#
# You can later put real attributed exchange/VASP addresses here.
# Do NOT guess a person's identity from a wallet.
VASP_DIRECTORY: Dict[str, Dict[str, Any]] = {
    # Example structure:
    #
    # "0xrealaddress": {
    #     "name": "Binance",
    #     "type": "exchange"
    # }
}


# ============================================================
# FASTAPI
# ============================================================

app = FastAPI(
    title="TraceX - Blockchain Forensic Automation Engine",
    version="2.0.0",
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# MODELS
# ============================================================

class TraceRequest(BaseModel):
    wallet_address: str
    max_hops: int = Field(default=3, ge=1, le=5)


# ============================================================
# HELPERS
# ============================================================

def validate_wallet(address: str) -> str:
    address = address.strip().lower()

    if not re.fullmatch(r"0x[a-f0-9]{40}", address):
        raise HTTPException(
            status_code=400,
            detail="Please enter a valid Ethereum wallet address.",
        )

    return address


def short_address(address: str) -> str:
    if not address:
        return ""

    if len(address) <= 16:
        return address

    return f"{address[:8]}...{address[-6:]}"


def safe_float(value: Any) -> float:
    try:
        return float(value or 0)
    except Exception:
        return 0.0


def format_asset(raw_asset: Any) -> str:
    asset = str(raw_asset or "ETH").strip()

    if not asset:
        return "ETH"

    # Remove obvious garbage generated by malformed metadata.
    if len(asset) > 20:
        return "TOKEN"

    return asset.upper()


def wei_to_eth(value: Any) -> float:
    try:
        return int(value or 0) / 10**18
    except Exception:
        return 0.0


def token_amount(value: Any, decimals: Any) -> float:
    try:
        raw = int(value or 0)
        dec = int(decimals if decimals is not None else 18)
        return raw / (10 ** dec)
    except Exception:
        return 0.0


# ============================================================
# ALCHEMY RPC
# ============================================================

def alchemy_rpc(method: str, params: List[Any]) -> Dict[str, Any]:
    if not ALCHEMY_URL:
        raise HTTPException(
            status_code=500,
            detail="ALCHEMY_API_KEY is missing in block/.env",
        )

    try:
        response = requests.post(
            ALCHEMY_URL,
            json={
                "jsonrpc": "2.0",
                "id": 1,
                "method": method,
                "params": params,
            },
            timeout=30,
        )

        response.raise_for_status()

        data = response.json()

    except requests.RequestException as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Alchemy request failed: {str(exc)}",
        )

    if "error" in data:
        raise HTTPException(
            status_code=502,
            detail=str(data["error"]),
        )

    return data.get("result", {})


# ============================================================
# FETCH ASSET TRANSFERS
# ============================================================

def fetch_transfers(
    address: str,
    direction: str,
    category: str,
    max_count: int = MAX_TX_PER_REQUEST,
) -> List[Dict[str, Any]]:

    params = [
        {
            "fromBlock": "0x0",
            "toBlock": "latest",
            "category": [category],
            "withMetadata": True,
            "excludeZeroValue": True,
            "maxCount": hex(min(max_count, 100)),
        }
    ]

    if direction == "from":
        params[0]["fromAddress"] = address
    else:
        params[0]["toAddress"] = address

    result = alchemy_rpc(
        "alchemy_getAssetTransfers",
        params,
    )

    return result.get("transfers", [])


# ============================================================
# NORMALIZE ALCHEMY TRANSFER
# ============================================================

def normalize_transfer(
    tx: Dict[str, Any],
    searched_wallet: str,
    hop: int,
) -> Optional[Dict[str, Any]]:

    source = str(tx.get("from") or "").lower()
    target = str(tx.get("to") or "").lower()

    if not source or not target:
        return None

    if not source.startswith("0x") or not target.startswith("0x"):
        return None

    raw_asset = tx.get("asset") or "ETH"

    if raw_asset == "0x":
        raw_asset = "ETH"

    asset = format_asset(raw_asset)

    amount = safe_float(tx.get("value"))

    if amount <= 0:
        return None

    src_res = resolve_entity(source)
    tgt_res = resolve_entity(target)
    print(f"API Address: {tx.get('from')} -> {source} -> {'matched' if src_res.get('known') else 'not matched'} -> {src_res.get('label')}")
    print(f"API Address: {tx.get('to')} -> {target} -> {'matched' if tgt_res.get('known') else 'not matched'} -> {tgt_res.get('label')}")

    return {
        "id": tx.get("hash")
        or f"{source[:10]}-{target[:10]}-{tx.get('blockNum')}",

        "hash": tx.get("hash"),

        "source": source,
        "target": target,

        "source_label": src_res.get("label") if src_res.get("known") else short_address(source),
        "target_label": tgt_res.get("label") if tgt_res.get("known") else short_address(target),

        "amount": amount,
        "asset": asset,

        "timestamp": (
            tx.get("metadata", {})
            .get("blockTimestamp")
        ),

        "block": tx.get("blockNum"),

        "category": tx.get("category"),

        "direction": (
            "outgoing"
            if source == searched_wallet
            else "incoming"
        ),

        "hop": hop,
    }


# ============================================================
# ENTITY RESOLVER & INDEX
# ============================================================

class EntityResolver:
    """
    Reusable resolver and index for all wallet addresses against /data.
    Maintains a persistent SQLite connection and an in-memory cache
    for ultra-fast O(1) repeated lookups across all addresses.
    """
    def __init__(self, db_path: Path):
        self.db_path = db_path
        self._conn = None
        self._cache: Dict[str, Dict[str, Any]] = {}
        self._init_db()

    def _init_db(self):
        if self.db_path and self.db_path.exists():
            try:
                self._conn = sqlite3.connect(
                    f"file:{self.db_path.resolve()}?mode=ro",
                    uri=True,
                    check_same_thread=False
                )
            except Exception:
                try:
                    self._conn = sqlite3.connect(
                        str(self.db_path),
                        check_same_thread=False
                    )
                except Exception as e:
                    print(f"Error opening exchange registry: {e}")

    def resolve(self, address: str) -> Dict[str, Any]:
        if not address:
            return {
                "address": "",
                "label": "Intermediary Wallet",
                "entity_type": "unknown",
                "known": False,
                "entity_resolved": None,
                "type": "Intermediary Wallet",
                "node_class": "intermediary",
                "display_name": "Intermediary Wallet",
                "is_exchange": False,
                "is_mixer": False,
                "attribution_method": "none",
                "source": None,
            }

        # Safe normalization: strip whitespace and lowercase
        norm_address = address.strip().lower()

        if norm_address in self._cache:
            return self._cache[norm_address]

        # 1. In-memory manual directory
        if norm_address in VASP_DIRECTORY:
            entry = VASP_DIRECTORY[norm_address]
            e_type = str(entry.get("type", "exchange")).lower()
            name = entry.get("name", "Known VASP")
            is_ex = (e_type == "exchange")
            is_mx = (e_type == "mixer")
            res = {
                "address": norm_address,
                "label": name,
                "entity_type": e_type,
                "known": True,
                "entity_resolved": name,
                "type": "Exchange" if is_ex else ("Mixer" if is_mx else "Known Entity"),
                "node_class": "exchange" if is_ex else ("mixer" if is_mx else "intermediary"),
                "display_name": name,
                "is_exchange": is_ex,
                "is_mixer": is_mx,
                "attribution_method": "vasp_directory",
                "source": "TraceX VASP Directory",
            }
            self._cache[norm_address] = res
            return res

        # 2. Database lookup using indexed address column
        if self._conn:
            try:
                cur = self._conn.cursor()
                row = cur.execute(
                    """
                    SELECT name, type, wallet_type, coin, network, source
                    FROM exchange_wallets
                    WHERE address = ?
                    LIMIT 1
                    """,
                    (norm_address,)
                ).fetchone()

                if row:
                    name, entity_type, wallet_type, coin, network, source = row
                    e_type_lower = str(entity_type or "exchange").lower()
                    is_ex = (
                        e_type_lower == "exchange"
                        or str(wallet_type or "").lower() in ("deposit", "hot", "cold")
                    )
                    is_mx = (e_type_lower == "mixer")
                    label_name = name or ("Known Exchange" if is_ex else "Known Entity")
                    res = {
                        "address": norm_address,
                        "label": label_name,
                        "entity_type": "exchange" if is_ex else ("mixer" if is_mx else e_type_lower),
                        "known": True,
                        "entity_resolved": label_name,
                        "type": "Exchange" if is_ex else ("Mixer" if is_mx else "Known Entity"),
                        "node_class": "exchange" if is_ex else ("mixer" if is_mx else "intermediary"),
                        "display_name": label_name,
                        "is_exchange": is_ex,
                        "is_mixer": is_mx,
                        "attribution_method": "local_registry",
                        "wallet_type": wallet_type,
                        "coin": coin,
                        "network": network,
                        "source": source or "Exchange Registry",
                    }
                    self._cache[norm_address] = res
                    return res
            except Exception as e:
                print(f"Database lookup error for {norm_address}: {e}")

        # 3. Unknown address
        res = {
            "address": norm_address,
            "label": "Intermediary Wallet",
            "entity_type": "unknown",
            "known": False,
            "entity_resolved": None,
            "type": "Intermediary Wallet",
            "node_class": "intermediary",
            "display_name": "Intermediary Wallet",
            "is_exchange": False,
            "is_mixer": False,
            "attribution_method": "none",
            "source": None,
        }
        self._cache[norm_address] = res
        return res

ENTITY_RESOLVER = EntityResolver(DB_PATH)

def resolve_entity(address: str) -> Dict[str, Any]:
    return ENTITY_RESOLVER.resolve(address)


# ============================================================
# FETCH BOTH SIDES
# ============================================================

def fetch_wallet_activity(
    wallet: str,
    hop: int,
) -> List[Dict[str, Any]]:

    transfers: List[Dict[str, Any]] = []

    # ERC20
    for direction in ("from", "to"):
        try:
            data = fetch_transfers(
                wallet,
                direction,
                "erc20",
            )

            for tx in data:
                normalized = normalize_transfer(
                    tx,
                    wallet,
                    hop,
                )

                if normalized:
                    transfers.append(normalized)

        except HTTPException:
            raise

    # Native ETH
    for direction in ("from", "to"):
        try:
            data = fetch_transfers(
                wallet,
                direction,
                "external",
            )

            for tx in data:
                normalized = normalize_transfer(
                    tx,
                    wallet,
                    hop,
                )

                if normalized:
                    transfers.append(normalized)

        except HTTPException:
            raise

    return transfers


# ============================================================
# RISK
# ============================================================

def calculate_node_risk(
    address: str,
    txs: List[Dict[str, Any]],
    searched_wallet: str,
) -> Tuple[int, List[str]]:

    outgoing = [
        tx for tx in txs
        if tx["source"] == address
    ]

    incoming = [
        tx for tx in txs
        if tx["target"] == address
    ]

    counterparties = set()

    for tx in outgoing:
        counterparties.add(tx["target"])

    for tx in incoming:
        counterparties.add(tx["source"])

    score = 0
    reasons: List[str] = []

    if len(txs) >= 20:
        score += 15
        reasons.append("High transaction activity")

    if len(counterparties) >= 5:
        score += 15
        reasons.append("Multiple counterparties")

    if len(outgoing) >= 5:
        score += 15
        reasons.append("Multiple outgoing destinations")

    total_in = sum(
        tx["amount"]
        for tx in incoming
    )

    total_out = sum(
        tx["amount"]
        for tx in outgoing
    )

    if total_in > 0 and total_out > 0:
        forwarding_ratio = (
            min(total_out / total_in, 1)
        )

        if forwarding_ratio >= 0.8:
            score += 20
            reasons.append("High forwarding ratio")

    if address == searched_wallet:
        score += 10
        reasons.append("Investigation wallet")

    score = min(score, 100)

    if score >= 70:
        status = "High"
    elif score >= 40:
        status = "Medium"
    else:
        status = "Low"

    return score, reasons


# ============================================================
# MAIN TRACE ENGINE
# ============================================================

def trace_wallet(
    searched_wallet: str,
    max_hops: int,
) -> Dict[str, Any]:

    visited = {
        searched_wallet
    }

    queue = deque([
        (
            searched_wallet,
            0,
        )
    ])

    all_transactions: List[Dict[str, Any]] = []

    wallet_hops: Dict[str, int] = {
        searched_wallet: 0
    }

    # --------------------------------------------------------
    # BFS MULTI-HOP TRACE
    # --------------------------------------------------------

    while queue:

        current_wallet, current_hop = queue.popleft()

        if current_hop >= max_hops:
            continue

        if len(visited) >= MAX_WALLETS:
            break

        activity = fetch_wallet_activity(
            current_wallet,
            current_hop,
        )

        # Deduplicate transactions
        existing_hashes = {
            tx.get("hash")
            for tx in all_transactions
            if tx.get("hash")
        }

        for tx in activity:

            if len(all_transactions) >= MAX_TOTAL_TX:
                break

            if (
                tx.get("hash")
                and tx["hash"] in existing_hashes
            ):
                continue

            all_transactions.append(tx)

            destination = tx["target"]

            # Only follow outgoing destinations.
            if (
                tx["source"] == current_wallet
                and destination not in visited
                and destination != searched_wallet
                and len(visited) < MAX_WALLETS
            ):
                visited.add(destination)

                wallet_hops[destination] = (
                    current_hop + 1
                )

                queue.append(
                    (
                        destination,
                        current_hop + 1,
                    )
                )

    # --------------------------------------------------------
    # REMOVE INVALID / DUPLICATE TRANSACTIONS
    # --------------------------------------------------------

    unique_transactions = {}

    for tx in all_transactions:

        key = (
            tx.get("hash")
            or (
                tx["source"],
                tx["target"],
                tx["amount"],
                tx["asset"],
            )
        )

        unique_transactions[key] = tx

    all_transactions = list(
        unique_transactions.values()
    )

    # --------------------------------------------------------
    # NODE METRICS
    # --------------------------------------------------------

    node_transactions: Dict[str, List[Dict[str, Any]]] = (
        defaultdict(list)
    )

    outgoing_by_node = defaultdict(float)
    incoming_by_node = defaultdict(float)
    flow_by_node = defaultdict(float)
    counterparties = defaultdict(set)

    for tx in all_transactions:

        source = tx["source"]
        target = tx["target"]

        node_transactions[source].append(tx)
        node_transactions[target].append(tx)

        outgoing_by_node[source] += tx["amount"]
        incoming_by_node[target] += tx["amount"]

        flow_by_node[source] += tx["amount"]
        flow_by_node[target] += tx["amount"]

        counterparties[source].add(target)
        counterparties[target].add(source)

    # --------------------------------------------------------
    # CREATE NODE SET
    # --------------------------------------------------------

    node_addresses = set(
        [searched_wallet]
        + list(node_transactions.keys())
    )

    nodes = []

    for address in node_addresses:

        entity = resolve_entity(address)

        node_txs = node_transactions.get(
            address,
            [],
        )

        risk_score, risk_reasons = calculate_node_risk(
            address,
            node_txs,
            searched_wallet,
        )

        is_exchange = entity.get("is_exchange", False)
        is_mixer = entity.get("is_mixer", False)
        entity_resolved = entity.get("entity_resolved", "Unknown")

        if is_exchange:

            display_name = (
                entity_resolved
                if entity_resolved != "Unknown"
                else "Known Exchange"
            )
            node_type = "Exchange"
            node_class = "exchange"

        elif address == searched_wallet:

            display_name = "Investigation Wallet"
            node_type = "Investigation Wallet"
            node_class = "investigation"

        elif is_mixer:

            display_name = (
                entity_resolved
                if entity_resolved != "Unknown"
                else "Mixer"
            )
            node_type = "Mixer"
            node_class = "mixer"

        else:

            display_name = "Intermediary Wallet"
            node_type = "Intermediary Wallet"
            node_class = "intermediary"

        nodes.append(
            {
                "id": address,

                "label": display_name,

                "display_name": display_name,

                "entity_resolved": (
                    entity_resolved
                    if entity_resolved != "Unknown"
                    else None
                ),

                "entity_type": entity.get("entity_type", "unknown"),

                "known": entity.get("known", False),

                "attribution_method": entity.get(
                    "attribution_method",
                    "none",
                ),

                "type": node_type,

                "node_class": node_class,

                "address": address,

                "full_address": address,

                "is_investigation_wallet": (
                    address == searched_wallet
                ),

                "risk_score": risk_score,

                "risk_status": (
                    "High"
                    if risk_score >= 70
                    else "Medium"
                    if risk_score >= 40
                    else "Low"
                ),

                "risk_reasons": risk_reasons,

                "is_exchange": is_exchange,

                "is_mixer": is_mixer,

                "hop": wallet_hops.get(
                    address,
                    1,
                ),

                "incoming_value": incoming_by_node[
                    address
                ],

                "outgoing_value": outgoing_by_node[
                    address
                ],

                "flow_value": flow_by_node[
                    address
                ],

                "counterparties": len(
                    counterparties[address]
                ),
            }
        )

    # --------------------------------------------------------
    # AGGREGATE EDGES
    # --------------------------------------------------------

    edge_groups: Dict[
        Tuple[str, str, str],
        Dict[str, Any]
    ] = {}

    for tx in all_transactions:

        key = (
            tx["source"],
            tx["target"],
            tx["asset"],
        )

        if key not in edge_groups:

            edge_groups[key] = {
                "id": (
                    f'{tx["source"]}-'
                    f'{tx["target"]}-'
                    f'{tx["asset"]}'
                ),

                "source": tx["source"],
                "target": tx["target"],

                "asset": tx["asset"],

                "amount": 0.0,

                "transaction_count": 0,

                "timestamp": tx["timestamp"],

                "latest_timestamp": tx[
                    "timestamp"
                ],

                "max_transaction": 0.0,

                "hop": tx["hop"],
            }

        group = edge_groups[key]

        group["amount"] += tx["amount"]

        group["transaction_count"] += 1

        group["max_transaction"] = max(
            group["max_transaction"],
            tx["amount"],
        )

        if tx["timestamp"]:
            group["latest_timestamp"] = (
                tx["timestamp"]
            )

    edges = []

    for edge in edge_groups.values():

        edges.append(
            {
                **edge,

                "label": (
                    f'{edge["amount"]:,.4f} '
                    f'{edge["asset"]}'
                ),

                "amount_label": (
                    f'{edge["amount"]:,.4f} '
                    f'{edge["asset"]}'
                ),

                "transactions": edge[
                    "transaction_count"
                ],
            }
        )

    # --------------------------------------------------------
    # PATTERNS
    # --------------------------------------------------------

    patterns = []

    for address in node_addresses:

        outgoing = [
            tx for tx in all_transactions
            if tx["source"] == address
        ]

        if len(outgoing) >= 3:

            destinations = {
                tx["target"]
                for tx in outgoing
            }

            if len(destinations) >= 2:

                patterns.append(
                    {
                        "type": "Fund Splitting",
                        "wallet": address,
                        "description": (
                            "Funds were distributed "
                            "towards multiple destinations."
                        ),
                    }
                )

    # --------------------------------------------------------
    # FUNDS BY ASSET
    # --------------------------------------------------------

    funds_by_asset = defaultdict(float)

    for tx in all_transactions:
        funds_by_asset[
            tx["asset"]
        ] += tx["amount"]

    # --------------------------------------------------------
    # ACTUAL HOPS
    # --------------------------------------------------------

    actual_hops = max(
        wallet_hops.values()
        or [0]
    )

    # --------------------------------------------------------
    # ROOT RISK
    # --------------------------------------------------------

    root_node = next(
        (
            node
            for node in nodes
            if node["id"] == searched_wallet
        ),
        None,
    )

    risk_score = (
        root_node["risk_score"]
        if root_node
        else 0
    )

    risk_status = (
        "High"
        if risk_score >= 70
        else "Medium"
        if risk_score >= 40
        else "Low"
    )

    # --------------------------------------------------------
    # RETURN
    # --------------------------------------------------------

    root_entity = resolve_entity(searched_wallet)

    return {
        "status": "success",

        "searched_wallet": searched_wallet,

        "entity_resolved": (
            root_entity.get("entity_resolved")
            if root_entity.get("entity_resolved") != "Unknown"
            else None
        ),

        "is_exchange": root_entity.get("is_exchange", False),

        "attribution_method": root_entity.get("attribution_method", "none"),

        "node_class": (
            "exchange"
            if root_entity.get("is_exchange", False)
            else "investigation"
        ),

        "display_name": (
            (root_entity.get("entity_resolved") or "Known Exchange")
            if root_entity.get("is_exchange", False)
            else "Investigation Wallet"
        ),

        "summary": {
            "risk_score": risk_score,

            "risk_status": risk_status,

            "total_nodes": len(nodes),

            "total_transactions": len(
                all_transactions
            ),

            "transactions_returned": len(
                all_transactions
            ),

            "hops_traced": actual_hops,

            "funds_by_asset": dict(
                funds_by_asset
            ),

            "total_funds": sum(
                funds_by_asset.values()
            ),
        },

        "topology": {
            "nodes": nodes,
            "edges": edges,
        },

        "transactions": all_transactions,

        "patterns": patterns,
    }


# ============================================================
# ROUTES
# ============================================================

@app.get("/")
def root():
    return {
        "service": "TraceX",
        "status": "running",
        "version": "2.0.0",
    }


@app.get("/health")
def health():
    return {
        "status": "ok",
        "engine_version": "2.0.0-horizontal-noise-filter",
        "alchemy_configured": bool(
            ALCHEMY_API_KEY
        ),
    }


@app.post("/api/v1/engine/trace")
def trace_endpoint(
    request: TraceRequest,
):

    wallet = validate_wallet(
        request.wallet_address
    )

    print("DB_PATH.resolve():", DB_PATH.resolve())
    print("DB_PATH.exists():", DB_PATH.exists())
    print("resolve_entity(wallet):", resolve_entity(wallet))

    try:

        return trace_wallet(
            wallet,
            request.max_hops,
        )

    except HTTPException:
        raise

    except Exception as exc:

        print(
            "TRACE ERROR:",
            repr(exc),
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Trace engine failed: "
                f"{str(exc)}"
            ),
        )